"""третья миграция

Revision ID: c86a3c10f530
Revises: cf2ad3540c6a
Create Date: 2023-07-08 02:54:05.501383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86a3c10f530'
down_revision = 'cf2ad3540c6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'company_name1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('company_name1', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
