"""вторая миграция

Revision ID: cf2ad3540c6a
Revises: 57f14ed2cd7a
Create Date: 2023-07-08 02:52:28.792742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2ad3540c6a'
down_revision = '57f14ed2cd7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('company_name1', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'company_name1')
    # ### end Alembic commands ###
